const router = require('express').Router();
const { requireAdmin } = require('../../middleware/admin.middleware');
const controller = require('./product.controller');
router.use(requireAdmin);
router.get('/', controller.list);
router.post('/', controller.create);
router.get('/:id', controller.detail);
router.patch('/:id', controller.update);
router.delete('/:id', controller.remove);
router.patch('/:id/stock', controller.stock);
module.exports = router;
