import React, {useState} from 'react';
import {KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {Ionicons} from '@react-native-vector-icons/ionicons/static';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAuth} from '../../features/auth/AuthContext';
import colors from '../../theme/colors';

function PasswordInput({label, value, onChangeText}) {
  const [visible, setVisible] = useState(false);
  return <><Text style={styles.label}>{label}</Text><View style={styles.inputWrap}><Ionicons name="lock-closed-outline" size={20} color={colors.textMuted} /><TextInput value={value} onChangeText={onChangeText} secureTextEntry={!visible} placeholder={`Enter ${label.toLowerCase()}`} placeholderTextColor={colors.textMuted} style={styles.input} /><Pressable hitSlop={8} onPress={() => setVisible(current => !current)}><Ionicons name={visible ? 'eye-off-outline' : 'eye-outline'} size={21} color={colors.textMuted} /></Pressable></View></>;
}

export default function RegisterScreen({navigation}) {
  const {register} = useAuth(); const [method, setMethod] = useState('email'); const [name, setName] = useState(''); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const submit = async () => {if (isSubmitting) return;const validIdentifier = method === 'email' ? /^\S+@\S+\.\S+$/.test(identifier) : /^\d{10}$/.test(identifier); if (name.trim().length < 2) return setError('Enter your full name.'); if (!validIdentifier) return setError(method === 'email' ? 'Enter a valid email address.' : 'Enter a valid 10-digit mobile number.'); if (password.length < 8) return setError('Password must contain at least 8 characters.'); if (password !== confirmPassword) return setError('Passwords do not match.'); setError(''); setIsSubmitting(true); try {await register({name: name.trim(), identifier: identifier.trim(), method, password, confirmPassword}); navigation.popTo('Tabs');} catch (registrationError) {setError(registrationError.message || 'Unable to register. Please try again.');} finally {setIsSubmitting(false);}};
  const switchMethod = next => {setMethod(next); setIdentifier(''); setError('');};
  return <SafeAreaView style={styles.container}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><Pressable onPress={navigation.goBack} style={styles.backButton}><Ionicons name="arrow-back" size={22} color={colors.primary} /></Pressable><Text style={styles.title}>Create your account</Text><Text style={styles.subtitle}>Join Big Vora for a faster shopping experience</Text><Text style={styles.label}>Full name</Text><View style={styles.inputWrap}><Ionicons name="person-outline" size={20} color={colors.textMuted} /><TextInput value={name} onChangeText={setName} autoCapitalize="words" placeholder="Enter your full name" placeholderTextColor={colors.textMuted} style={styles.input} /></View><View style={styles.methodTabs}>{['mobile', 'email'].map(item => <Pressable key={item} onPress={() => switchMethod(item)} style={[styles.methodTab, method === item && styles.methodTabActive]}><Text style={[styles.methodText, method === item && styles.methodTextActive]}>{item === 'mobile' ? 'Use mobile' : 'Use email'}</Text></Pressable>)}</View><Text style={styles.label}>{method === 'mobile' ? 'Mobile number' : 'Email address'}</Text><View style={styles.inputWrap}><Ionicons name={method === 'mobile' ? 'call-outline' : 'mail-outline'} size={20} color={colors.textMuted} /><TextInput value={identifier} onChangeText={setIdentifier} autoCapitalize="none" keyboardType={method === 'mobile' ? 'phone-pad' : 'email-address'} maxLength={method === 'mobile' ? 10 : undefined} placeholder={method === 'mobile' ? '10-digit mobile number' : 'you@example.com'} placeholderTextColor={colors.textMuted} style={styles.input} /></View><PasswordInput label="Password" value={password} onChangeText={setPassword} /><PasswordInput label="Confirm password" value={confirmPassword} onChangeText={setConfirmPassword} />{Boolean(error) && <View style={styles.errorBox}><Ionicons name="alert-circle-outline" size={17} color="#C83E3E" /><Text style={styles.errorText}>{error}</Text></View>}<Pressable onPress={submit} disabled={isSubmitting} accessibilityState={{disabled:isSubmitting,busy:isSubmitting}} style={styles.primaryButton}><Text style={styles.primaryText}>{isSubmitting?'Creating account...':'Create account'}</Text><Ionicons name="arrow-forward" size={18} color={colors.background} /></Pressable><View style={styles.loginRow}><Text style={styles.loginPrompt}>Already have an account?</Text><Pressable onPress={() => navigation.replace('Login')}><Text style={styles.loginLink}> Sign in</Text></Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

const styles = StyleSheet.create({container: {flex: 1, backgroundColor: colors.background}, flex: {flex: 1}, content: {paddingHorizontal: 24, paddingBottom: 30}, backButton: {width: 42, height: 42, alignItems: 'center', justifyContent: 'center', marginTop: 4, borderRadius: 14, backgroundColor: colors.surface}, title: {marginTop: 20, color: colors.primary, fontSize: 27, fontWeight: '800'}, subtitle: {marginTop: 7, marginBottom: 27, color: colors.textMuted, fontSize: 13}, label: {marginBottom: 7, color: colors.primary, fontSize: 12, fontWeight: '700'}, inputWrap: {height: 53, flexDirection: 'row', alignItems: 'center', marginBottom: 16, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 15, backgroundColor: colors.surface}, input: {flex: 1, marginLeft: 10, color: colors.text, fontSize: 14}, methodTabs: {flexDirection: 'row', marginBottom: 18, padding: 4, borderRadius: 14, backgroundColor: colors.surface}, methodTab: {flex: 1, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 11}, methodTabActive: {backgroundColor: colors.primary}, methodText: {color: colors.textMuted, fontSize: 11, fontWeight: '700'}, methodTextActive: {color: colors.background}, errorBox: {flexDirection: 'row', alignItems: 'center', marginTop: 1, padding: 10, borderRadius: 11, backgroundColor: '#FFF0F0'}, errorText: {flex: 1, marginLeft: 7, color: '#C83E3E', fontSize: 11}, primaryButton: {height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 18, borderRadius: 16, backgroundColor: colors.accent}, primaryText: {marginRight: 9, color: colors.background, fontSize: 15, fontWeight: '800'}, loginRow: {flexDirection: 'row', justifyContent: 'center', marginTop: 20}, loginPrompt: {color: colors.textMuted, fontSize: 12}, loginLink: {color: colors.accent, fontSize: 12, fontWeight: '800'}});
