import React from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Ionicons} from '@react-native-vector-icons/ionicons/static';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useCart} from '../../../features/cart/CartContext';
import colors from '../../../theme/colors';
import CartQuantityControl from '../../../components/cart/CartQuantityControl';

const money=value=>'\u20B9'+Number(value||0).toLocaleString('en-IN');
export default function ProductDetailsScreen({navigation,route}){
 const product=route.params?.product;const{items,addToCart,updateQuantity,favourites,toggleFavourite}=useCart();
 const quantity=items.find(item=>item.id===product?.id)?.quantity||0;const isFavourite=favourites.some(item=>item.id===product?.id);
 if(!product)return null;
 const sellingPrice=Number(product.priceValue??product.price);const mrp=Number(product.mrp||sellingPrice);const discount=Number(product.discountPercent)||(mrp>sellingPrice?Math.round(((mrp-sellingPrice)/mrp)*100):0);
 return <SafeAreaView style={styles.container}><View style={styles.header}><Pressable onPress={navigation.goBack} style={styles.headerButton}><Ionicons name="arrow-back" size={22} color={colors.primary}/></Pressable><Text style={styles.headerTitle}>Product details</Text><Pressable onPress={()=>toggleFavourite(product)} style={styles.headerButton}><Ionicons name={isFavourite?'heart':'heart-outline'} size={22} color={isFavourite?colors.accent:colors.primary}/></Pressable></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
 <View style={[styles.visual,{backgroundColor:product.tint??'#EDF3FF'}]}>{discount>0&&<View style={styles.saleBadge}><Text style={styles.saleText}>{discount}% OFF</Text></View>}{product.images?.length?<ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{product.images.map(uri=><Image key={uri} source={{uri}} resizeMode="contain" style={styles.image}/>)}</ScrollView>:<Ionicons name={product.icon??'bag-handle'} size={126} color={colors.primaryLight}/>}</View>
 <Text style={styles.name}>{product.name}</Text><View style={styles.priceRow}><Text style={styles.price}>{money(sellingPrice)}</Text>{mrp>sellingPrice&&<Text style={styles.oldPrice}>{money(mrp)}</Text>}{discount>0&&<Text style={styles.discount}>{discount}% off</Text>}</View><Text style={styles.taxText}>Inclusive of all taxes</Text><View style={styles.divider}/><Text style={styles.sectionTitle}>Product details</Text><Text style={styles.description}>{product.description||'Product details are being updated.'}</Text>
 {Boolean(product.rules?.length)&&<><Text style={styles.rulesHeading}>Product promises</Text><View style={styles.benefits}>{product.rules.map(rule=><View key={rule.id} style={styles.benefit}><Ionicons name={rule.icon||'checkmark-circle-outline'} size={23} color={colors.accent}/><Text style={styles.benefitText}>{rule.title}</Text><Text style={styles.benefitDescription}>{rule.description}</Text></View>)}</View></>}
 </ScrollView><View style={styles.footer}><CartQuantityControl quantity={quantity} onIncrease={()=>addToCart(product)} onDecrease={()=>updateQuantity(product.id,-1)} style={styles.quantity}/><Pressable onPress={()=>navigation.navigate('Tabs',{screen:'Cart'})} style={styles.cartButton}><Ionicons name="cart-outline" size={20} color={colors.background}/><Text style={styles.cartText}>View cart</Text></Pressable></View></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},header:{height:64,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16},headerButton:{width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.surface},headerTitle:{color:colors.primary,fontSize:18,fontWeight:'800'},content:{paddingBottom:110},visual:{height:330,alignItems:'center',justifyContent:'center',marginHorizontal:20,borderRadius:26,overflow:'hidden'},image:{width:330,height:300},saleBadge:{position:'absolute',zIndex:2,top:17,left:17,paddingHorizontal:10,paddingVertical:6,borderRadius:8,backgroundColor:colors.accent},saleText:{color:colors.background,fontSize:9,fontWeight:'800'},name:{marginTop:20,paddingHorizontal:20,color:colors.primary,fontSize:25,fontWeight:'800'},priceRow:{flexDirection:'row',alignItems:'center',marginTop:11,paddingHorizontal:20},price:{color:colors.primary,fontSize:22,fontWeight:'800'},oldPrice:{marginLeft:9,color:colors.textMuted,fontSize:12,textDecorationLine:'line-through'},discount:{marginLeft:9,color:'#179A63',fontSize:11,fontWeight:'800'},taxText:{marginTop:4,paddingHorizontal:20,color:colors.textMuted,fontSize:10},divider:{height:1,marginHorizontal:20,marginVertical:21,backgroundColor:colors.border},sectionTitle:{paddingHorizontal:20,color:colors.primary,fontSize:17,fontWeight:'800'},description:{marginTop:9,paddingHorizontal:20,color:colors.textMuted,fontSize:12,lineHeight:19},rulesHeading:{marginTop:22,paddingHorizontal:20,color:colors.primary,fontSize:15,fontWeight:'800'},benefits:{flexDirection:'row',flexWrap:'wrap',marginHorizontal:14,marginTop:10},benefit:{width:'31%',alignItems:'center',marginHorizontal:'1.15%',marginBottom:9,padding:11,borderRadius:14,backgroundColor:colors.surface},benefitText:{marginTop:7,color:colors.primary,fontSize:9,fontWeight:'700',textAlign:'center'},benefitDescription:{marginTop:4,color:colors.textMuted,fontSize:8,lineHeight:12,textAlign:'center'},footer:{position:'absolute',right:0,bottom:0,left:0,flexDirection:'row',alignItems:'center',padding:14,borderTopWidth:1,borderTopColor:colors.border,backgroundColor:colors.background},quantity:{marginRight:12},cartButton:{flex:1,height:52,flexDirection:'row',alignItems:'center',justifyContent:'center',borderRadius:16,backgroundColor:colors.accent},cartText:{marginLeft:8,color:colors.background,fontSize:14,fontWeight:'800'}});
