import React, {useState} from 'react';
import {KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {Ionicons} from '@react-native-vector-icons/ionicons/static';
import {SafeAreaView} from 'react-native-safe-area-context';
import colors from '../../theme/colors';

export default function AdminFormScreen({navigation,title,fields,onSubmit,initialValues={},children,submitDisabled=false}){
  const [values,setValues]=useState(Object.fromEntries(fields.map(field=>[field.key,initialValues[field.key]||''])));const[error,setError]=useState('');
  const[saving,setSaving]=useState(false);
  const save=async()=>{if(saving||submitDisabled)return;const missing=fields.find(field=>field.required&&!values[field.key].trim());if(missing){setError(`${missing.label} is required.`);return;}setError('');setSaving(true);try{await onSubmit(values);navigation.goBack();}catch(saveError){setError(saveError.message||'Unable to save. Please try again.');}finally{setSaving(false);}};
  return <SafeAreaView style={styles.container}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.header}><Pressable onPress={navigation.goBack} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.primary}/></Pressable><Text style={styles.title}>{title}</Text><View style={styles.spacer}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{children}{fields.map(field=><View key={field.key}><Text style={styles.label}>{field.label}{field.required?' *':''}</Text><View style={[styles.inputWrap,field.multiline&&styles.multiWrap]}><Ionicons name={field.icon} size={20} color={colors.textMuted}/><TextInput value={values[field.key]} onChangeText={text=>setValues(current=>({...current,[field.key]:text}))} placeholder={field.placeholder} placeholderTextColor={colors.textMuted} keyboardType={field.keyboardType||'default'} multiline={field.multiline} textAlignVertical={field.multiline?'top':'center'} style={[styles.input,field.multiline&&styles.multiInput]}/></View></View>)}{Boolean(error)&&<Text style={styles.error}>{error}</Text>}<Pressable onPress={save} disabled={saving||submitDisabled} style={styles.save}><Text style={styles.saveText}>{saving?'Saving...':'Save'}</Text><Ionicons name="checkmark" size={20} color={colors.background}/></Pressable></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.surface},flex:{flex:1},header:{height:65,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20,backgroundColor:colors.background},back:{width:40,height:40,alignItems:'center',justifyContent:'center',borderRadius:13,backgroundColor:colors.surface},title:{color:colors.primary,fontSize:18,fontWeight:'800'},spacer:{width:40},content:{padding:20,paddingBottom:40},label:{marginTop:8,marginBottom:7,color:colors.primary,fontSize:12,fontWeight:'700'},inputWrap:{height:54,flexDirection:'row',alignItems:'center',marginBottom:14,paddingHorizontal:14,borderWidth:1,borderColor:colors.border,borderRadius:15,backgroundColor:colors.background},multiWrap:{height:112,alignItems:'flex-start',paddingTop:16},input:{flex:1,marginLeft:10,color:colors.text,fontSize:13},multiInput:{height:82,paddingTop:0},error:{marginBottom:10,color:'#C83E3E',fontSize:11},save:{height:54,flexDirection:'row',alignItems:'center',justifyContent:'center',marginTop:10,borderRadius:16,backgroundColor:colors.accent},saveText:{marginRight:8,color:colors.background,fontSize:14,fontWeight:'800'}});
