import React,{useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{Ionicons}from'@react-native-vector-icons/ionicons/static';
import{SafeAreaView}from'react-native-safe-area-context';
import{useAuth}from'../../../features/auth/AuthContext';
import colors from'../../../theme/colors';

export default function ChangePasswordScreen({navigation}){
 const{changePassword}=useAuth();const[form,setForm]=useState({currentPassword:'',newPassword:'',confirmPassword:''});const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const submit=async()=>{if(saving)return;if(!form.currentPassword)return setError('Enter your current password.');if(form.newPassword.length<8)return setError('New password must contain at least 8 characters.');if(form.newPassword===form.currentPassword)return setError('Choose a new password different from your current password.');if(form.newPassword!==form.confirmPassword)return setError('New passwords do not match.');setSaving(true);setError('');try{await changePassword(form);setForm({currentPassword:'',newPassword:'',confirmPassword:''});Alert.alert('Password changed','Your password was updated successfully.',[{text:'OK',onPress:navigation.goBack}]);}catch(e){setError(e.message||'Unable to change password.');}finally{setSaving(false);}};
 return <SafeAreaView style={s.container}><View style={s.header}><Pressable onPress={navigation.goBack} style={s.back}><Ionicons name="arrow-back" size={22} color={colors.primary}/></Pressable><Text style={s.title}>Change password</Text><View style={s.space}/></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{[['currentPassword','Current password'],['newPassword','New password'],['confirmPassword','Confirm new password']].map(([key,label])=><View key={key}><Text style={s.label}>{label}</Text><TextInput value={form[key]} onChangeText={value=>set(key,value)} secureTextEntry autoCapitalize="none" autoCorrect={false} maxLength={72} style={s.input}/></View>)}<Text style={s.note}>Use at least 8 characters. Avoid reusing a password from another service.</Text>{Boolean(error)&&<Text style={s.error}>{error}</Text>}<Pressable disabled={saving} onPress={submit} style={[s.button,saving&&s.disabled]}><Text style={s.buttonText}>{saving?'Updating...':'Update password'}</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:colors.surface},header:{height:64,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,backgroundColor:colors.background},back:{width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.surface},title:{color:colors.primary,fontSize:19,fontWeight:'800'},space:{width:42},content:{padding:20},label:{marginBottom:7,color:colors.primary,fontSize:12,fontWeight:'700'},input:{height:52,marginBottom:17,paddingHorizontal:14,borderWidth:1,borderColor:colors.border,borderRadius:14,color:colors.text,backgroundColor:colors.background},note:{color:colors.textMuted,fontSize:11,lineHeight:17},error:{marginTop:15,color:'#C83E3E',fontSize:12},button:{height:54,alignItems:'center',justifyContent:'center',marginTop:24,borderRadius:16,backgroundColor:colors.accent},disabled:{opacity:.5},buttonText:{color:colors.background,fontSize:14,fontWeight:'800'}});
