import React from 'react';
import {Alert,Linking,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Ionicons} from '@react-native-vector-icons/ionicons/static';
import {SafeAreaView} from 'react-native-safe-area-context';
import {SUPPORT_CONTACT} from '../../../config/support';
import colors from '../../../theme/colors';

const contacts=[
  {key:'email',title:'Email support',value:SUPPORT_CONTACT.email,icon:'mail-outline',url:`mailto:${SUPPORT_CONTACT.email}?subject=Big%20Vora%20Support`},
  {key:'phone',title:'Call support',value:SUPPORT_CONTACT.phoneDisplay,icon:'call-outline',url:`tel:${SUPPORT_CONTACT.phone}`},
  {key:'whatsapp',title:'WhatsApp support',value:SUPPORT_CONTACT.phoneDisplay,icon:'logo-whatsapp',url:`https://wa.me/${SUPPORT_CONTACT.whatsapp}?text=Hello%20Big%20Vora%2C%20I%20need%20help.`},
];
async function openContact(url){try{if(!await Linking.canOpenURL(url))throw new Error();await Linking.openURL(url);}catch{Alert.alert('Unable to open','This contact option is not available on your device.');}}
export default function HelpSupportScreen({navigation}){return <SafeAreaView style={styles.container}><View style={styles.header}><Pressable onPress={navigation.goBack} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.primary}/></Pressable><Text style={styles.headerTitle}>Help & support</Text><View style={styles.space}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.heroIcon}><Ionicons name="headset-outline" size={32} color={colors.background}/></View><Text style={styles.heroTitle}>How can we help?</Text><Text style={styles.heroText}>Our support team can help with your account, orders, payments, delivery and returns.</Text></View><Text style={styles.sectionTitle}>Contact Big Vora</Text><View style={styles.card}>{contacts.map((item,index)=><Pressable key={item.key} accessibilityRole="button" onPress={()=>openContact(item.url)} style={[styles.row,index<contacts.length-1&&styles.border]}><View style={styles.icon}><Ionicons name={item.icon} size={22} color={colors.accent}/></View><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text selectable style={styles.value}>{item.value}</Text></View><Ionicons name="open-outline" size={18} color={colors.textMuted}/></Pressable>)}</View><View style={styles.note}><Ionicons name="time-outline" size={19} color={colors.primary}/><Text style={styles.noteText}>Please include your order number when contacting us about an order. Response times may vary outside business hours.</Text></View></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.surface},header:{height:64,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,backgroundColor:colors.background},back:{width:42,height:42,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.surface},headerTitle:{color:colors.primary,fontSize:19,fontWeight:'800'},space:{width:42},content:{padding:20,paddingBottom:40},hero:{alignItems:'center',padding:24,borderRadius:23,backgroundColor:colors.primary},heroIcon:{width:62,height:62,alignItems:'center',justifyContent:'center',borderRadius:20,backgroundColor:colors.accent},heroTitle:{marginTop:15,color:colors.background,fontSize:21,fontWeight:'800'},heroText:{marginTop:8,color:'#C8D3E2',fontSize:12,lineHeight:18,textAlign:'center'},sectionTitle:{marginTop:24,marginBottom:11,color:colors.primary,fontSize:16,fontWeight:'800'},card:{overflow:'hidden',borderRadius:19,backgroundColor:colors.background},row:{minHeight:76,flexDirection:'row',alignItems:'center',padding:14},border:{borderBottomWidth:1,borderBottomColor:colors.border},icon:{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:'#FFF0E8'},copy:{flex:1,marginLeft:12},title:{color:colors.primary,fontSize:13,fontWeight:'800'},value:{marginTop:4,color:colors.textMuted,fontSize:11},note:{flexDirection:'row',alignItems:'flex-start',marginTop:16,padding:14,borderRadius:15,backgroundColor:'#EDF2FF'},noteText:{flex:1,marginLeft:9,color:colors.textMuted,fontSize:10,lineHeight:16}});
